// Jenkinsfile (Declarative Pipeline)
pipeline {
    agent any
    stages {
        stage('Build jar') {
            steps {
                script {
                        sh 'sh ./microservices/service02/build-image.sh'
                }
            }
        }
    }
    post {
        always {
            deleteDir() /* clean up our workspace */
        }
    }
}
